### ISSUE TITLE
Add dynamic glacier outline download functionality

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#10]
Identical to #9 apart from the type of data. See #9 for the rationale.

The same (long term) issue is present here with data having to be downloaded manually, but could be solved by just automatically downloading from the https://npolar.no website instead. 

https://github.com/eliskasieglova/SvalbardSurges/blob/2fa3e532d2c66c008f7e178d2ca80d806e4aed1f/main.py#L137-L140

Here's the link to the dataset repo:
https://data.npolar.no/dataset/f6afca5c-6c95-4345-9e52-cfe2f24c7078

And here's the direct link to the glacier outline dataset:
https://api.npolar.no/dataset/f6afca5c-6c95-4345-9e52-cfe2f24c7078/_file/3df9512e5a73841b1a23c38cf4e815e3

`geopandas` can read shapefiles within zipfiles, so we don't have to worry about extracting them!

**Comment by eliskasieglova** [comment]
Added in [c51c77c](https://github.com/eliskasieglova/SvalbardSurges/commit/c51c77cc986ae327aa1afe04044ab97406c8e1bf).
