### ISSUE TITLE
Split up the code into multiple modules

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#13]
For now, having just one `main.py` works fine. In the long-term, however, this will become quite cumbersome and hard to navigate. When the time comes, I recommend splitting the code up into smaller modules that will increase readability.

For example:
- `svalbardsurges/`
  - `analysis.py`  For hypsometric binning, change detection, etc.
  - `plotting.py`  For making figures
  - `utilities.py`   For utility functions like generic downloading, cache handling, etc.
  - `inputs`  A submodule for all the different inputs
      - `dems.py`
      - `is2.py`
      - `outlines.py`

Then the `main.py` function simply imports the `svalbardsurges` package and calls the necessary functions from within.

See some projects I've worked on for inspiration:
- https://github.com/VAW-SwissTerra/terradem
- https://github.com/erikmannerfelt/ADSvalbard. Note that here I'm in the middle of migrating from a single `main.py` to a package! The `main.py` in comparison looks awful now!

**Comment by eliskasieglova** [comment]
Fixed in [b90d3b4](https://github.com/eliskasieglova/SvalbardSurges/commit/b90d3b4bdb4abbf5b2ca739522cbf87b49ae0350).
