### ISSUE TITLE
Move the nan filtering to the elevation change function

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#14]
A good dH filtering step is now in the hypsometric interpolation function. This is the first time it's needed (right now at least), but I think this would fit better inside the elevation change function instead, as this filtering should always apply, not just when hypsometric binning is performed.

https://github.com/eliskasieglova/SvalbardSurges/blob/d543748abb2777c6ec8f6556027e04ec46de0901/main.py#L285-L286

Speaking of filtering, the whole reason for that line was that nodata values are sampled. I wonder if this can be fixed by changing the sampling strategy a bit. The `Raster.value_at_coords` method has a `masked` keyword that should mask out any nodata.
https://geoutils.readthedocs.io/en/stable/gen_modules/geoutils.Raster.value_at_coords.html#geoutils.Raster.value_at_coords

A masked array cannot (to my knowledge) be set to an xarray dataset, so we need the `.filled(np.nan)` method to replace masked values with nans:
```python
dem.value_at_coords(is2.easting, is2.northing, masked=True).filled(np.nan)
```
This might solve the nodata problem completely if we're lucky!

**Comment by eliskasieglova** [comment]
Fixed in [b90d3b4](https://github.com/eliskasieglova/SvalbardSurges/commit/b90d3b4bdb4abbf5b2ca739522cbf87b49ae0350).
