### ISSUE TITLE
`gao_label` seems incorrect

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#15]
The glacier outlines from Geyman et al., 2022 (for some reason labelled GAO) seem to be saved as if it was a NetCDF instead of a zipfile. Also its name is `is2` which of course sounds like IceSat-2!

https://github.com/eliskasieglova/SvalbardSurges/blob/aa4f21d6e8599149a4fbdacbe67ca26be5279e10/download_urls.py#L14

**Comment by eliskasieglova** [comment]
This was in a file that was not supposed to be commited! File deleted now.
