### ISSUE TITLE
Make sure the `figures/` directory exists.

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#16]
I checked the hypsometric plotting function and it saves to a `figures/` directory which is great! This will however fail if the `figures/` directory doesn't already exist.

https://github.com/eliskasieglova/SvalbardSurges/blob/4430e918477a9d65e368e21f37f8a392c050abfc/svalbardsurges/plotting.py#L61-L63

There are two ways of fixing this:
```python
Path("figures/").mkdir(exist_ok=True)
```
```python
if not os.path.isdir("figures/"):
    os.mkdir("figures/")

```

**Comment by eliskasieglova** [comment]
Fixed in [c51c77c](https://github.com/eliskasieglova/SvalbardSurges/commit/c51c77cc986ae327aa1afe04044ab97406c8e1bf).
