### ISSUE TITLE
Add dynamic DEM download function

### ISSUE THREAD

**Issue by erikmannerfelt** [eliskasieglova/SvalbardSurges#9]
In the long term (a few weeks), we should strive for making the code as repeatable as possible. What I mean by that is:
1. It should be possible to run on new machines (if we want to run it on a server)
2. The functionality should not be specific to any computer (it should work the same on any machine)
3. It should be easy to switch glacier if we want to observe a new one.

An example of non-repeatability is the hardcoding of paths that we've downloaded manually.
I want to underscore that we've of course done this for brevity and making sure we could get a fast initial result, so this is just a natural evolution from that!

https://github.com/eliskasieglova/SvalbardSurges/blob/2fa3e532d2c66c008f7e178d2ca80d806e4aed1f/main.py#L172-L173

What would instead be better to do is:
1. Assign the download URLs in the script or in an auxiliary file
2. Download the file to the cache when required
3. Have all the paths relate to the cache path, meaning if 1 and 2 works, the script would work on any new machine.

Downloading data with python is a bit of a mess. To my knowledge, there's no one-liner for good downloading. In one of my projects, I wrote this script:
https://github.com/erikmannerfelt/ADSvalbard/blob/091b231c3eea25239ec40ad6c58155ff51826b19/adsvalbard/utilities.py#L105-L131

A modification of this may work directly in here:
```python
# toplevel
import tempfile
import shutil
import os
from pathlib import Path
import requests  # Might need to be installed.
# / toplevel

def download_large_file(url: str, filename: str | None = None, directory: Path | str | None = None) -> Path:
    """
    Download a file from the requested URL.

    Parameters
    ----------
    - url:
        The URL to download the file from.
    - filename:
        The output filename of the file. Defaults to the basename of the URL.
    - directory:
        The directory to save the file in. Defaults to `cache/`
    
    Returns
    -------
    A path to the downloaded file.
    """

    # If `directory` is defined, make sure it's a path. If it's not defined, default to `cache/`
    if isinstance(directory, (str, Path)):
        out_dir = Path(directory)
    else:
        out_dir = Path("cache/")

    if filename is not None:
        out_path = out_dir.joinpath(filename)
    else:
        out_path = out_dir.joinpath(os.path.basename(url))

    # If the file already exists, skip downloading it.
    if not out_path.is_file():
        # Open a data stream from the URL. This means not everything has to be kept in memory.
        with requests.get(url, stream=True) as request:
            # Stop and raise an exception if there's a problem.
            request.raise_for_status()

            # Save the file to a temporary directory first. The file is constantly appended to due to the streaming
            # Therefore, if the stream is cancelled, the file is not complete and should be dropped.
            with tempfile.TemporaryDirectory() as temp_dir:

                temp_path = Path(temp_dir).joinpath("temp.file")
                # Write the data stream as it's received
                with open(temp_path, "wb") as outfile:
                    shutil.copyfileobj(request.raw, outfile)

                # When the download is done, move the file to its ultimate location.
                shutil.move(temp_path, out_path)

    return out_path
```

Note that I'm using type annotations for the arguments and return types. This is optional but really helps in documenting the function. For python versions before 3.10 (I think), the first line in the script has to be this to support type annotations:
```python
from __future__ import annotations
```
But since we specified the `environment.yml` to have a minimum supported python version of 3.10 (like my foreshadowing? 🤓), this is not needed. I just wanted to add this in case we run into issues with older python versions!

**Comment by erikmannerfelt** [comment]
Oh and one challenge will be that the DEMs come zipped. Rasterio/variete/xdem can read files in zipfiles easily so this won't be an issue!

**Comment by erikmannerfelt** [comment]
We can copy and modify the function `build_npi_mosaic` from my ArcticDEM project:

https://github.com/erikmannerfelt/ADSvalbard/blob/43997ef87addb924390cf66820b6661b13795a04/main.py

**Comment by eliskasieglova** [comment]
Added in [c51c77c](https://github.com/eliskasieglova/SvalbardSurges/commit/c51c77cc986ae327aa1afe04044ab97406c8e1bf).
